language: java
dist: xenial
jdk:
    - openjdk11
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=${CODACY_PROJECT_TOKEN} -DapiToken=${CODACY_API_TOKEN}
