language: java
dist: xenial
jdk:
    - openjdk11
cache:
  directories:
    - $HOME/.m2/repository
env:
  global:
    - JAVA_OPTS="-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2"    
script:
 - mvn test -Dtest=!de.urmel_dl.dbt.events.TestIdentifierExtractorEventHandler#testIdentfierExtract
after_success:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=${CODACY_PROJECT_TOKEN} -DapiToken=${CODACY_API_TOKEN}
