<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.mycore</groupId>
    <artifactId>mycore-parent</artifactId>
    <version>58</version>
  </parent>
  <artifactId>dbt-parent</artifactId>
  <version>2025.12-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>DBT: Parent</name>
  <url>http://www.db-thueringen.de</url>
  <licenses>
    <license>
      <name>GNU General Public License, version 3</name>
      <url>http://www.gnu.org/licenses/gpl-3.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <modules>
    <module>dbt-module</module>
    <module>dbt-it</module>
  </modules>
  <issueManagement>
    <system>JIRA</system>
    <url>https://mycore.atlassian.net/browse/DBT</url>
  </issueManagement>
  <scm>
    <connection>scm:git:https://github.com/ThULB/dbt.git</connection>
    <developerConnection>scm:git:https://github.com/ThULB/dbt.git</developerConnection>
    <url>https://github.com/ThULB/dbt/tree/master</url>
    <tag>HEAD</tag>
  </scm>
  <properties>
    <grunt.projectBase>${project.build.directory}/grunt</grunt.projectBase>
    <java.target.version>21</java.target.version>
    <lesscss.compress>true</lesscss.compress>
    <maven.compiler.failOnWarning>true</maven.compiler.failOnWarning>
    <maven.compiler.release>${java.target.version}</maven.compiler.release>
    <media.projectBase>${project.build.directory}/media</media.projectBase>
    <mir-layout-assets>${project.build.directory}/mir-layout-assets</mir-layout-assets>
    <mir.version>2025.12.2-SNAPSHOT</mir.version>
    <npm.version>10.9.2</npm.version>
    <rcclient.projectBase>${project.build.directory}/rcclient</rcclient.projectBase>
    <template.assetsdir>${template.targetdir}/dbt/assets</template.assetsdir>
    <template.cssdir>${template.targetdir}/dbt/css</template.cssdir>
    <template.mirassetsdir>${mir-layout-assets}/META-INF/resources/mir-layout</template.mirassetsdir>
    <template.targetdir>${project.build.directory}/classes/META-INF/resources</template.targetdir>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>license-maven-plugin</artifactId>
        </plugin>
        <plugin>
          <groupId>de.thetaphi</groupId>
          <artifactId>forbiddenapis</artifactId>
          <configuration>
            <failOnUnsupportedJava>false</failOnUnsupportedJava>
            <failOnMissingClasses>false</failOnMissingClasses>
            <failOnUnresolvableSignatures>false</failOnUnresolvableSignatures>
            <bundledSignatures>
              <bundledSignature>jdk-unsafe</bundledSignature>
              <bundledSignature>jdk-deprecated</bundledSignature>
            </bundledSignatures>
          </configuration>
        </plugin>
        <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself. -->
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <versionRange>[1.6,)</versionRange>
                    <goals>
                      <goal>update-project-license</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <versionRange>[2.8,)</versionRange>
                    <goals>
                      <goal>copy</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>de.thetaphi</groupId>
                    <artifactId>forbiddenapis</artifactId>
                    <versionRange>[1.6.1,)</versionRange>
                    <goals>
                      <goal>check</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <ciManagement>
    <system>bamboo</system>
    <url>https://bamboo.mycore.de/browse/DBT</url>
  </ciManagement>
  <repositories>
    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>central-portal-snapshots</id>
      <name>Central Portal Snapshots</name>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>central-portal-snapshots</id>
      <name>Central Portal Snapshots</name>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </pluginRepository>
  </pluginRepositories>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.mycore.mir</groupId>
        <artifactId>mir-parent</artifactId>
        <version>${mir.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>org.eclipse.persistence.moxy</artifactId>
        <version>4.0.8</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.parsson</groupId>
        <artifactId>parsson</artifactId>
        <version>1.1.7</version>
        <scope>runtime</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
