<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.mycore</groupId>
    <artifactId>dbt-parent</artifactId>
    <version>2025.12-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>dbt-it</artifactId>
  <packaging>jar</packaging>
  <name>DBT: Integration Tests</name>
  <description>combines all modules and runs integration tests</description>
  <properties>
    <MCR.AppName>mir</MCR.AppName>
    <MCR.Home.Integration>${project.build.directory}/mycore-home</MCR.Home.Integration>
    <argLine />
    <cargo.jvmargs>-DMCR.Home=${MCR.Home.Integration}
      -DMCR.AppName=${MCR.AppName}
      -Djava.awt.headless=true</cargo.jvmargs>
    <cargo.rmi.port>9105</cargo.rmi.port>
    <cargo.servlet.port>9107</cargo.servlet.port>
    <cargo.tomcat.ajp.port>9106</cargo.tomcat.ajp.port>
    <dbt.classifications.dir>${project.basedir}/../dbt-module/src/main/resources/setup/classifications</dbt.classifications.dir>
    <dbt.setup.dir>${project.basedir}/../dbt-module/src/main/resources/setup</dbt.setup.dir>
    <failsafe.arg />
    <it.host>127.0.0.1</it.host>
    <maven.deploy.skip>true</maven.deploy.skip>
    <maven.install.skip>true</maven.install.skip>
    <solr.home>${MCR.Home.Integration}/solr-home</solr.home>
    <solr.port>9108</solr.port>
  </properties>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <executions>
          <execution>
            <id>clean-integration</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <excludeDefaultDirectories>true</excludeDefaultDirectories>
              <filesets>
                <fileset>
                  <directory>${MCR.Home.Integration}</directory>
                </fileset>
              </filesets>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack-cli</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <includeArtifactIds>mir-cli</includeArtifactIds>
              <includeTypes>tar.gz</includeTypes>
              <outputDirectory>${project.build.directory}/dependency</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>copy-test-libs</id>
            <goals>
              <goal>copy</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <outputDirectory>${MCR.Home.Integration}/${MCR.AppName}/lib</outputDirectory>
              <artifactItems>
                <artifactItem>
                  <groupId>com.h2database</groupId>
                  <artifactId>h2</artifactId>
                  <version>2.2.224</version>
                </artifactItem>
                <artifactItem>
                  <groupId>org.mycore</groupId>
                  <artifactId>dbt-module</artifactId>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
          <execution>
            <id>unpack-solr-zip</id>
            <goals>
              <goal>unpack</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/solr-zip</outputDirectory>
              <artifactItems>
                <artifactItem>
                  <groupId>org.mycore.mir</groupId>
                  <artifactId>mir-webapp</artifactId>
                  <type>war</type>
                  <includes>WEB-INF/classes/solr-home.zip</includes>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>unzip-solr-home</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <target>
                <unzip dest="${project.build.directory}/solr-template" src="${project.build.directory}/solr-zip/WEB-INF/classes/solr-home.zip" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-test-config</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <outputDirectory>${MCR.Home.Integration}/${MCR.AppName}</outputDirectory>
              <resources>
                <resource>
                  <directory>src/test/integration</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.mycore.plugins</groupId>
        <artifactId>solr-runner-maven-plugin</artifactId>
        <configuration>
          <solrHome>${solr.home}</solrHome>
          <solrHomeTemplate>${project.build.directory}/solr-template</solrHomeTemplate>
          <solrPort>${solr.port}</solrPort>
        </configuration>
        <executions>
          <execution>
            <id>start-solr</id>
            <goals>
              <goal>copyHome</goal>
              <goal>start</goal>
            </goals>
            <phase>pre-integration-test</phase>
          </execution>
          <execution>
            <goals>
              <goal>stop</goal>
            </goals>
            <phase>post-integration-test</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <configuration>
          <environmentVariables>
            <JAVA_OPTS>-DMCR.Home=${MCR.Home.Integration}</JAVA_OPTS>
          </environmentVariables>
          <workingDirectory>${project.build.directory}/dependency/mir-cli-${mir.version}</workingDirectory>
        </configuration>
        <executions>
          <execution>
            <id>setup-solr-cloud</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <executable>bin${file.separator}mir.${script.suffix}</executable>
              <arguments>process ${project.build.directory}/dependency/mir-cli-${mir.version}/config/setup-solrcloud.txt</arguments>
            </configuration>
          </execution>
          <execution>
            <id>setup-cli</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <executable>bin${file.separator}setup.${script.suffix}</executable>
            </configuration>
          </execution>
          <execution>
            <id>setup-dbt-classifications</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <executable>bin${file.separator}mir.${script.suffix}</executable>
              <arguments>process ${MCR.Home.Integration}/${MCR.AppName}/setup-dbt-classifications.txt</arguments>
            </configuration>
          </execution>
          <execution>
            <id>setup-dbt-acl</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <phase>pre-integration-test</phase>
            <configuration>
              <executable>bin${file.separator}mir.${script.suffix}</executable>
              <arguments>process ${MCR.Home.Integration}/${MCR.AppName}/setup-dbt-acl.txt</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.cargo</groupId>
        <artifactId>cargo-maven3-plugin</artifactId>
        <configuration>
          <container>
            <containerId>tomcat10x</containerId>
            <artifactInstaller>
              <groupId>org.apache.tomcat</groupId>
              <artifactId>tomcat</artifactId>
              <version>${tomcat.version}</version>
              <type>tar.gz</type>
            </artifactInstaller>
          </container>
          <deployables>
            <deployable>
              <groupId>org.mycore.mir</groupId>
              <artifactId>mir-webapp</artifactId>
              <type>war</type>
              <properties>
                <context>/${MCR.AppName}</context>
              </properties>
            </deployable>
          </deployables>
          <configuration>
            <home>${project.build.directory}/catalina-base</home>
            <properties>
              <cargo.jvmargs>${cargo.jvmargs}</cargo.jvmargs>
              <cargo.rmi.port>${cargo.rmi.port}</cargo.rmi.port>
              <cargo.servlet.port>${cargo.servlet.port}</cargo.servlet.port>
              <cargo.tomcat.ajp.port>${cargo.tomcat.ajp.port}</cargo.tomcat.ajp.port>
              <cargo.tomcat.uriencoding>UTF-8</cargo.tomcat.uriencoding>
              <!-- fixes IIIF identifier encoding issues -->
              <cargo.start.jvmargs>-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true</cargo.start.jvmargs>
            </properties>
            <users>
              <user>
                <name>mir</name>
                <password>mirgehtsgut</password>
                <roles>
                  <role>usera</role>
                </roles>
              </user>
            </users>
          </configuration>
        </configuration>
        <executions>
          <execution>
            <id>start-container</id>
            <goals>
              <goal>start</goal>
            </goals>
            <phase>pre-integration-test</phase>
          </execution>
          <execution>
            <id>stop-container</id>
            <goals>
              <goal>stop</goal>
            </goals>
            <phase>post-integration-test</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <argLine>@{argLine} ${failsafe.arg}</argLine>
          <systemPropertyVariables>
            <project.build.directory>${project.build.directory}</project.build.directory>
            <it.port>${cargo.servlet.port}</it.port>
            <it.context>${MCR.AppName}</it.context>
            <!-- MCRSeleniumTestBase property -->
            <HostName>${it.host}</HostName>
            <ResultFolder>${project.build.directory}/failsafe-reports/</ResultFolder>
            <java.awt.headless>true</java.awt.headless>
            <solr.port>${solr.port}</solr.port>
            <mcr.it.solr.core.main>dbt</mcr.it.solr.core.main>
            <mcr.it.solr.core.classifications>dbt-classifications</mcr.it.solr.core.classifications>
          </systemPropertyVariables>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
        <executions>
          <execution>
            <id>integration-tests</id>
            <goals>
              <goal>integration-test</goal>
            </goals>
          </execution>
          <execution>
            <id>verify-results</id>
            <goals>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.ibm.icu</groupId>
      <artifactId>icu4j</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.solr</groupId>
      <artifactId>solr-solrj</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore</groupId>
      <artifactId>dbt-module</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore</groupId>
      <artifactId>mycore-base</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore</groupId>
      <artifactId>mycore-solr</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore</groupId>
      <artifactId>selenium-utils</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore.mir</groupId>
      <artifactId>mir-cli</artifactId>
      <type>tar.gz</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore.mir</groupId>
      <artifactId>mir-it</artifactId>
      <version>${mir.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mycore.mir</groupId>
      <artifactId>mir-webapp</artifactId>
      <type>war</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-remote-driver</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-support</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <profiles>
    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>windows</family>
        </os>
      </activation>
      <properties>
        <script.suffix>bat</script.suffix>
      </properties>
    </profile>
    <profile>
      <id>unix</id>
      <activation>
        <os>
          <family>unix</family>
        </os>
      </activation>
      <properties>
        <script.suffix>sh</script.suffix>
      </properties>
    </profile>
  </profiles>
</project>
