name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Verify
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v3
    with:
      ff-site-goal: ''
      ff-os: 'ubuntu-24.04'
      ff-jdk: '21'
      ff-goal: '-P run-its verify'
      ff-site-run: false
      failure-upload-path: |
          ./**/surefire-reports
          ./**/failsafe-reports
          ./**/screenshots
          ./**/*error*.log
          ./**/*test.log
      matrix-exclude: >
        [
          {"os": "macOS-latest"},
          {"os": "windows-latest"},
          {"jdk": "8"},
          {"jdk": "17"},
          {"os": "ubuntu-latest", "jdk": "21"}
        ]
